# Generated by Django 2.1.4 on 2018-12-31 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resepti', '0002_auto_20181231_0503'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='ingred_amts',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
    ]
