# Generated by Django 2.1.4 on 2019-01-01 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resepti', '0006_auto_20190101_2233'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredient',
            name='quantity',
            field=models.DecimalField(decimal_places=2, max_digits=7, null=True),
        ),
    ]
