# Generated by Django 2.1.4 on 2019-01-01 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resepti', '0007_ingredient_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='step',
            name='text',
            field=models.TextField(max_length=255),
        ),
    ]
