# Generated by Django 2.1.4 on 2019-01-02 04:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resepti', '0008_auto_20190101_2304'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ingredient',
            name='volume',
        ),
    ]
