# Generated by Django 2.1.4 on 2019-01-06 02:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resepti', '0011_ingredamount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ingredient',
            name='quantity',
        ),
        migrations.RemoveField(
            model_name='ingredient',
            name='recipe',
        ),
        migrations.RemoveField(
            model_name='ingredient',
            name='weight',
        ),
    ]
