# Generated by Django 2.1.4 on 2019-01-06 10:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resepti', '0012_auto_20190106_0239'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ingredamount',
            old_name='ing',
            new_name='ingredient',
        ),
    ]
