# Generated by Django 2.1.4 on 2019-01-07 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resepti', '0013_auto_20190106_1039'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ingredient',
            old_name='itype',
            new_name='category',
        ),
        migrations.AddField(
            model_name='ingredient',
            name='calories',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='ingredient',
            name='density',
            field=models.DecimalField(decimal_places=8, max_digits=12, null=True),
        ),
    ]
