# Generated by Django 2.1.4 on 2019-01-07 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resepti', '0014_auto_20190107_0311'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ingredient',
            old_name='calories',
            new_name='calories_per_each',
        ),
        migrations.AddField(
            model_name='ingredient',
            name='calories_per_gram',
            field=models.IntegerField(default=0),
        ),
    ]
